# Generated by Django 3.1.2 on 2021-08-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postexpsurveymodel',
            name='q19',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexpsurveymodel',
            name='q20',
            field=models.TextField(blank=True, null=True),
        ),
    ]
