# Generated by Django 2.1.5 on 2020-09-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_gpshistoricaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentDataStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
