# Generated by Django 2.1.5 on 2020-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_experimentdatastorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participantid', models.CharField(blank=True, max_length=100, null=True)),
                ('taskid', models.CharField(blank=True, max_length=100, null=True)),
                ('trust', models.IntegerField(blank=True, null=True)),
                ('transparency', models.IntegerField(blank=True, null=True)),
                ('workload', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
