# Generated by Django 2.1.5 on 2020-09-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0005_questionnairemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantStatusModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participantid', models.CharField(blank=True, max_length=100, null=True)),
                ('participantindex', models.CharField(blank=True, max_length=100, null=True)),
                ('participantname', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('taskstatus', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
