# Generated by Django 2.1.5 on 2020-09-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0006_participantstatusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantstatusmodel',
            name='participantindex',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
