# Generated by Django 2.1.5 on 2020-09-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0007_auto_20200913_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX1_mental',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX2_physical',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX3_temporal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX4_performance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX5_effort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX6_frustration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='trans1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='trans2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='trans3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='trans4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='trans5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='trust1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='trust2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='trust3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='trust4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='trust5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
