# Generated by Django 3.1.2 on 2020-10-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0008_auto_20200917_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairemodel',
            name='scene_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
