# Generated by Django 3.1.2 on 2020-10-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0009_questionnairemodel_scene_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnairemodel',
            old_name='scene_id',
            new_name='sceneid',
        ),
    ]
