# Generated by Django 3.1.2 on 2020-12-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0012_postexpsurveymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postexpsurveymodel',
            name='q2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postexpsurveymodel',
            name='q3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
