# Generated by Django 3.2.10 on 2022-04-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0014_auto_20220103_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P10_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P11_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P12_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P13_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P14_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P15_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P1_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P2_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P3_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P4_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P5_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P6_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P7_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P8_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='NASATLX_P9_X',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
